name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:production
        if: always()
      - name: linting ts
        run: npm run lint:ts
        if: always()
      - name: linting CSS
        run: npm run stylelint
        if: always()
      - name: unit tests
        run: npm run unit
        if: always()
      - name: build storybook
        run: npm run build-storybook
      - name: screenshot testing
        run: npm run test:ui:ci