#name: linting-testing-building
#on: [ push ]
#
#jobs:
#    pipeline:
#        runs-on: windows-2019
##            strategy:
##                matrix:
##                    node-version: [ 18.8.1 ]
#        steps:
#            -   uses: actions/checkout@v3
#            -   name: Starting Node.js
#                uses: actions/setup-node@v3
#                with:
#                    node-version: 18
#            -   name: install modules
#                run: npm install
#            -   name: build production project
#                run: npm run build:production
#            -   name: linting ts
#                run: npm run lint:ts
#            -   name: linting CSS
#                run: npm run stylelint
#            -   name: unit tests
#                run: npm run unit
#            -   name: build storybook
#                run: npm run build-storybook
#            -   name: screenshot testing
#                run: npm run test:ui:ci

name: linting, testing, building
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
permissions:
    contents: write
    pages: write
    id-token: write
concurrency:
    group: "pages"
    cancel-in-progress: true
jobs:
    build-and-ui-testing:
        runs-on: ubuntu-latest
        concurrency: ci-${{ github.ref }}
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        strategy:
            matrix:
                node-version: [ 18.x ]
        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm ci
            - name: build production project
              run: npm run build:production
              if: always()
            - name: build storybook
              run: npm run build-storybook
              if: always()
            - name: screenshot testing
              run: npm run test:ui:ci
              if: always()
            - name: Generate HTML report
              run: npm run test:ui:report
              if: always()
            - name: Setup Pages
              uses: actions/configure-pages@v2
              if: always()
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              if: always()
              with:
                  path: '.loki'
            - name: Deploy to GitHub Pages
              id: deployment
              if: always()
              uses: actions/deploy-pages@v1

    checks:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 18.x ]
        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm ci
            - name: linting typescript
              run: npm run lint:ts
              if: always()
            - name: linting css
              run: npm run stylelint
            - name: unit testing
              if: always()
              run: npm run unit
